INSERT INTO bored (activity, challenge, category) 
VALUES 
('Read a book on a new topic', 3, 'education'),
('Take an online course ', 7, 'education'),
('Learn a new language', 8, 'education'),
('Watch a documentary', 2, 'education'),
('Attend a lecture or seminar', 5, 'education'),
('Research a historical event', 4, 'education'),
('Read a book on a new topic', 3, 'education'),
('Go for a walk or hike', 1, 'recreational'),
('Play a board game or card game', 2, 'recreational'),
('Watch a movie or TV show', 1, 'recreational'),
('Visit a museum or art gallery', 3, 'recreational'),
('Try a new sport or exercise routine', 6, 'recreational'),
('Play video games', 2, 'recreational'),
('Take a scenic drive or road trip', 5, 'recreational'),
('Explore a new city or town', 6, 'recreational'),
('Go to a theme park or amusement park', 7, 'recreational'),
('Have a picnic in the park', 2, 'recreational'),
('Call or video chat with a friend or family member', 1, 'social'),
('Plan a virtual hangout with friends', 2, 'social'),
('Attend a social event or party', 4, 'social'),
('Join a club or group with similar interests', 5, 'social'),
('Volunteer at a local organization', 6, 'social'),
('Attend a networking event', 7, 'social'),
('Host a dinner party or potluck', 5, 'social'),
('Attend a concert or music festival', 6, 'social'),
('Participate in a group activity like yoga or dance class', 4, 'social'),
('Join a book club', 3, 'social'),
('Donate to a charity of your choice', 1, 'charity'),
('Volunteer at a local shelter or food bank', 5, 'charity'),
('Participate in a charity walk or run', 6, 'charity'),
('Organize a fundraiser for a cause you care about', 7, 'charity'),
('Write letters to soldiers or hospital patients', 2, 'charity'),
('Help clean up your local community', 4, 'charity'),
('Donate blood or plasma', 6, 'charity'),
('Participate in a charity auction or raffle', 5, 'charity'),
('Mentor someone in need of guidance', 7, 'charity'),
('Sponsor a child in need through an organization', 8, 'charity'),
('Try a new recipe', 3, 'cooking'),
('Bake cookies or cupcakes', 4, 'cooking'),
('Host a dinner party or potluck', 5, 'cooking'),
('Meal prep for the week', 6, 'cooking'),
('Make homemade pasta or bread', 7, 'cooking'),
('Learn to make sushi or other international cuisine', 8, 'cooking'),
('Experiment with vegetarian or vegan cooking', 6, 'cooking'),
('Create a signature cocktail or mocktail', 5, 'cooking'),
('Make your own jam or preserves', 7, 'cooking'),
('Host a cooking competition with friends', 6, 'cooking'),
('Take a bubble bath or hot shower', 1, 'relaxation'),
('Meditate or practice yoga', 3, 'relaxation'),
('Read a book in bed', 2, 'relaxation'),
('Listen to calming music or nature sounds', 1, 'relaxation'),
('Get a massage or spa treatment', 8, 'relaxation'),
('Take a nap or rest in a hammock', 2, 'relaxation'),
('Practice deep breathing exercises', 3, 'relaxation'),
('Watch the sunset or sunrise', 2, 'relaxation'),
('Go stargazing or watch the moonrise', 4, 'relaxation'),
('Spend time in nature, like at a park or beach', 3, 'relaxation'),
('Learn to play a new instrument', 8, 'music'),
('Attend a concert or music festival', 5, 'music'),
('Create a playlist for a specific mood or occasion', 2, 'music'),
('Sing karaoke with friends', 3, 'music'),
('Join a local choir or band', 6, 'music'),
('Write your own song or lyrics', 7, 'music'),
('Attend an open mic night', 5, 'music'),
('Listen to music from a different culture or era', 2, 'music'),
('Dance to your favorite songs', 1, 'music'),
('Participate in a music workshop or class', 4, 'music');